### PR TITLE
Bump to 3.4.0.Final, simplify config/docs

### PR DESCRIPTION
**Pull request by skjolber**

### CODE REVIEW

**Comment by thomasdarimont** [comment]
@skjolber I completly missed that and did not see notifications for the PR /o\

**Comment by skjolber** [comment]
@thomasdarimont Okey, I've since moved away from Keycloak, if you want, manually copy the desired changes (if any) and close this PR.

**Comment by thomasdarimont** [comment]
@skjolber ok thanks for your contribution!

May I ask why you move away from Keycloak? Did you find a better IAM solution?

**Comment by skjolber** [comment]
Yes, we rather bought an OpenID solution as a service (at Auth0). Keycloak was introduced before my time, and there was quite lot of hassle related to running it in Kubernetes. It might be more 'cloud friendly now', however we are in the process of shutting it down.

**Pull request closed without merging**
